#!/usr/bin/env bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
AEROSPACE="$(command -v aerospace)"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar display=all position=top height=40 blur_radius=0 color=0x00000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding AeroSpace Workspace Indicators #####

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change
sketchybar --add event aerospace_focus_change

# Keep startup independent from AeroSpace. At login SketchyBar may start before
# AeroSpace has opened its socket, and a live query here can stall the config.
AEROSPACE_WORKSPACES="1 2 3 B G O Q"

for sid in $AEROSPACE_WORKSPACES
do
  space=(
    icon="$sid"
    icon.padding_left=7
    icon.padding_right=7
    label.font="sketchybar-app-font:Regular:16.0"
    label.padding_left=0
    label.padding_right=4
    label.drawing=off
    click_script="$AEROSPACE workspace $sid"
  )
  focused_window=(
    drawing=off
    padding_left=0
    padding_right=5
    icon.font="sketchybar-app-font:Regular:16.0"
    icon.padding_left=2
    icon.padding_right=3
    label.font="Hack Nerd Font:Bold:13.0"
    label.padding_left=0
    label.padding_right=4
    label.max_chars=18
  )
  space_bracket=(
    background.color=0x40ffffff
    background.corner_radius=5
    background.height=25
    background.padding_left=0
    background.padding_right=0
    background.drawing=off
  )
  sketchybar --add item space."$sid" left \
             --set space."$sid" "${space[@]}" \
             --add item space_focus."$sid" left \
             --set space_focus."$sid" "${focused_window[@]}" \
             --add bracket space_bracket."$sid" space."$sid" space_focus."$sid" \
             --set space_bracket."$sid" "${space_bracket[@]}"
done

sketchybar --add item aerospace_workspace_observer left \
           --set aerospace_workspace_observer \
                 drawing=off \
                 update_freq=5 \
                 script="$PLUGIN_DIR/aerospace_workspace_monitor.sh" \
           --subscribe aerospace_workspace_observer \
                       aerospace_workspace_change \
                       aerospace_monitor_change \
                       aerospace_focus_change \
                       front_app_switched \
                       display_change \
                       system_woke

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           --add item system_stats right \
           --set system_stats update_freq=5 \
                              icon.drawing=off \
                              script="$PLUGIN_DIR/system_stats.sh"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
